### ISSUE TITLE
getting 400 on this summoner name `절대충성꼬봉`

### ISSUE THREAD

**Issue by yawhide** [jwalton/lol-js#13]
Hello,

I am calling "getSummonerByNames" with this name: "절대충성꼬봉" and I am getting a 400. I manually tried the api explorer from riot using that same name and I get back the correct data 
```{"절대충성꼬봉": {
   "id": 31995663,
   "name": "절대충성꼬봉",
   "profileIconId": 28,
   "revisionDate": 1455772897000,
   "summonerLevel": 30
}}```

**Comment by yawhide** [comment]
also, i have found that names that are not ascii are not working with getSummonersByNames (but it isn't returning an error which is weird)

here are some examples:
jáýce
ðémøn
émerald
pãwz

**Comment by jwalton** [comment]
You're finding all kinds of really interesting problems.  :)  I'll try to get to looking through some of these on the weekend.  If you're interested in trying to debug some of these yourself, though, have a read through https://github.com/jwalton/lol-js/blob/master/docs/development.md, which should give you a pretty good overview of how things work.

**Comment by jwalton** [comment]
This is really weird.  I tried your `jáýce` example.  If I put a console.log() in to see what URL I'm passing to `request`, I see:

    https://na.api.pvp.net/api/lol/na/v1.4/summoner/by-name/jáýce?api_key=...

which is exactly right, but I get back a 404.  I'm guessing `request` is doing something awful here.  :/

**Comment by jwalton** [comment]
Aha.  A well placed `encodeURIComponent` seems to fix it.  I'll have a fix published in just a sec.

**Comment by yawhide** [comment]
so you had to urlencode the summoner name?

**Comment by jwalton** [comment]
Yeah.  I'm guessing Chrome does this automagically under the hood when you
type this into the URL bar or some such.

**Comment by yawhide** [comment]
thanks for looking into it

**Comment by jwalton** [comment]
Published in 2.0.2.

**Comment by yawhide** [comment]
still getting 404s for certain names (but the list got smaller lol)

pãwz
judë
당신을사랑

**Comment by yawhide** [comment]
Ok sorry i deleted, here is my real issue:

test code:
`RiotApi.getSummonersByName('na', _.uniq([
'ðémøn',
'émerald',
'jáýce',
'ðémøn',
'tënshi',
'émerald',
'prïde',
'saphíra',
'sadboyray',
'judë',
'kidø',
'térrror',
'antilopemasquée',
'nìkólài',
'mısery',
'fántasy',
'hybrídízatíon',
'détritus',
'당신을사랑',
'takeitslobro',
'macabré',
'magïc',
'baltø',
'ðémøn',
'당신을사랑',
'judë',
'davidprinting',
'kyöko',
'macabré',
'mısery',
'magïc',
'gods11y',
'pãwz']), function (err, results) {
  console.log(err, results)
})`

output:

```
null { 'ðémøn': null,
  'émerald': null,
  'jáýce': null,
  'tënshi': null,
  'prïde': null,
  'saphíra': null,
  sadboyray: null,
  'judë': null,
  'kidø': null,
  'térrror': null,
  'antilopemasquée': null,
  'nìkólài': null,
  'mısery': null,
  'fántasy': null,
  'hybrídízatíon': null,
  'détritus': null,
  '당신을사랑': null,
  takeitslobro: null,
  'macabré': null,
  'magïc': null,
  'baltø': null,
  davidprinting: null,
  'kyöko': null,
  gods11y: null,
  'pãwz': null }
```

here is what riot gives back for `pãwz`:

```
{"pãwz": {
   "id": 27429926,
   "name": "Pãwz",
   "profileIconId": 1016,
   "revisionDate": 1455939098000,
   "summonerLevel": 30
}}
```

**Comment by jwalton** [comment]
Is this still failing for you on v2.0.2?  Your example above works for me.  It doesn't find all of them (doesn't find "davidprinting", for example, but neither does a direct query to the Riot API.)

**Comment by yawhide** [comment]
yeah, my package.json says v2.0.2, do i need to clear redis maybe?

**Comment by yawhide** [comment]
is there a way to only clear the getSummerByNames cache and not the rest?

**Comment by jwalton** [comment]
I have never tried this, but I think you can with:

```
redis-cli --raw keys "*summonerByName*" | xargs redis-cli del
```

You could also swap to the in-memory cache temporarily.

**Comment by yawhide** [comment]
k thanks. it can now find them
